package id.org.test.ms.shared.auth;

public enum UserRole {
	
	SYSTEM("ROLE_SYSTEM"),
	ADMIN("ROLE_ADMIN"),
	ADMIN_FINANCE("ROLE_ADMIN_FINANCE"),
	ACCOUNT("ROLE_ACCOUNT"),
	ACCOUNT_PRO("ROLE_ACCOUNT_PRO"),
	STORE_ADMIN("ROLE_STORE_ADMIN"),
	CASHIER("ROLE_CASHIER"),
	PIC("ROLE_PIC"),
	ACCOUNT_TRIAL("ROLE_ACCOUNT_TRIAL"),
	ADMIN_DEV("ROLE_ADMIN_DEV"),
	ACCOUNT_PRO_INTERNAL("ROLE_ACCOUNT_PRO_INTERNAL"),
	ADMIN_CS("ROLE_ADMIN_CS"),
	ADMIN_MARKETING("ROLE_ADMIN_MARKETING"),
	ADMIN_CS_SUPER("ROLE_ADMIN_CS_SUPER"),
	ADMIN_MARKETING_SUPER("ROLE_ADMIN_MARKETING_SUPER"),
	ADMIN_SALES_REGIONAL_MANAGER("ROLE_ADMIN_SALES_REGIONAL_MANAGER"),
	ADMIN_MERCHANT_ACQUSITION("ROLE_ADMIN_MERCHANT_ACQUSITION"),
	//BANGKU
	DEBITUR("ROLE_DEBITUR"),
	IU("ROLE_IU"),
	OFFICER("ROLE_OFFICER"),
	;

	
	private String roleName;
	
	private UserRole(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleName() {
		return roleName;
	}

}
